### ISSUE TITLE
Please stop spamming

### ISSUE THREAD

**Issue by gvanrossum** [feramhq/feram#30]
We've received four different trivial PRs from this tool now for four different repos. (The last one was https://github.com/dropbox/changes-artifacts/pull/1.) Those all have requested us to star this project if we like those PRs. The opposite is the case, so please (a) stop spamming us, and (b) consider this the equivalent of a negative star if there was such a thing.

Those PRs were all sent by @ronbak -- unclear if that's a bot or someone connected to your project or not.

**Comment by ronbak** [comment]
Hey Guido,
sorry if feels like spam to you. (Ok I guess the Feram default message is indeed a little spammy. We'll improve it in future versions!)
Feram however only creates the commits and I personally reviewed them and created the pull requests, because all of them seemed worthwhile to me!
Your coworkers also seemed to be happy about the pull requests: https://github.com/dropbox/pyston/pull/1389

I just saw that the changes repo is no longer maintained and I guess this means you're not interested in pull requests for this repo. However, it's kind of hard to tell. We already asked GitHub to make it possible to disable pull requests for archived repos, but so far they've only ignored us. It would make it much easier to communicate if pull requests are welcomed or not…

So I really don't want to be annoying, but I don't really know what "stop spamming us" means. Is "us" dropbox, or a sub-department of dropbox or just a few repos? Cause - like I said - many people (including some of your co-workers) really liked our pull requests.

**Comment by ronbak** [comment]
But please don't get me wrong, I'm really sorry if I annoyed you, I just wanted to help!
If this doesn't feel like help to you, I clearly have to change something.
I'd be happy to hear your thoughts on how to make Feram more helpful!

**Comment by gvanrossum** [comment]
I don't have the time or the energy to explain it. Just don't use any more Dropbox projects as guinea pigs.
